<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="../common/taglib.jsp" %>
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>系统管理 - 图书馆管理系统</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/v2.css"></head>
<body class="v2-body"><div class="v2-layout">
<jsp:include page="v2-sidebar.jsp"><jsp:param name="active" value="system"/></jsp:include>
<main class="v2-main">
    <div class="v2-page-head"><div><h1>系统管理</h1><p>管理员账号与操作日志。</p></div></div>
    <section class="v2-card"><h2>新增管理员</h2><form class="v2-form" method="post" action="${pageContext.request.contextPath}/admin/v2/system/admins/add"><div><label>用户名</label><input class="v2-input" name="username" required></div><div><label>密码</label><input class="v2-input" type="password" name="password" required></div><div><label>姓名</label><input class="v2-input" name="realName" required></div><div><label>角色</label><select class="v2-select" name="role"><option value="ADMIN">普通管理员</option><option value="SUPER_ADMIN">超级管理员</option></select></div><div><label>手机</label><input class="v2-input" name="phone"></div><div><label>邮箱</label><input class="v2-input" name="email"></div><button class="v2-btn primary" type="submit">新增管理员</button></form></section>
    <section class="v2-card"><h2>管理员列表</h2><table class="v2-table"><tr><th>ID</th><th>用户名</th><th>姓名</th><th>角色</th><th>手机</th><th>邮箱</th><th>状态</th><th>操作</th></tr><c:forEach items="${admins}" var="a"><tr><td>${a.id}</td><td>${a.username}</td><td>${a.realName}</td><td>${a.role}</td><td>${a.phone}</td><td>${a.email}</td><td><span class="v2-tag ${a.status==1?'ok':'danger'}">${a.status==1?'启用':'禁用'}</span></td><td><a class="v2-btn danger" href="${pageContext.request.contextPath}/admin/v2/system/admins/disable/${a.id}" onclick="return confirm('确认禁用该管理员？')">禁用</a></td></tr></c:forEach></table></section>
    <section class="v2-card"><h2>操作日志</h2><form class="v2-form three" method="get" action="${pageContext.request.contextPath}/admin/v2/system"><div><label>关键词</label><input class="v2-input" name="keyword" value="${keyword}"></div><div><label>模块</label><input class="v2-input" name="module" value="${module}"></div><button class="v2-btn primary" type="submit">查询</button></form><table class="v2-table"><tr><th>时间</th><th>用户</th><th>模块</th><th>操作</th><th>IP</th></tr><c:forEach items="${logs}" var="l"><tr><td>${fn:replace(l.createTime, 'T', ' ')}</td><td>${l.operatorName}</td><td>${l.module}</td><td>${l.operation}</td><td>${l.ip}</td></tr></c:forEach><c:if test="${empty logs}"><tr><td colspan="5" class="v2-empty">暂无日志</td></tr></c:if></table></section>
</main></div></body></html>
